# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=-municode $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Buildings 6.0.0/Resources/C-Sources" -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=WaterCooledChillerExample_WaterCooledChillerExample7 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=7 -DOMC_NUM_NONLINEAR_SYSTEMS=23 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lryu -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lsz -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/Irvan/OneDrive/Dokumen/GitHub/WaterCooledChillerExample"
MAINFILE=WaterCooledChillerExample.WaterCooledChillerExample7.c
MAINOBJ=WaterCooledChillerExample.WaterCooledChillerExample7.o
CFILES=WaterCooledChillerExample.WaterCooledChillerExample7_functions.c WaterCooledChillerExample.WaterCooledChillerExample7_records.c \
WaterCooledChillerExample.WaterCooledChillerExample7_01exo.c WaterCooledChillerExample.WaterCooledChillerExample7_02nls.c WaterCooledChillerExample.WaterCooledChillerExample7_03lsy.c WaterCooledChillerExample.WaterCooledChillerExample7_04set.c WaterCooledChillerExample.WaterCooledChillerExample7_05evt.c WaterCooledChillerExample.WaterCooledChillerExample7_06inz.c WaterCooledChillerExample.WaterCooledChillerExample7_07dly.c \
WaterCooledChillerExample.WaterCooledChillerExample7_08bnd.c WaterCooledChillerExample.WaterCooledChillerExample7_09alg.c WaterCooledChillerExample.WaterCooledChillerExample7_10asr.c WaterCooledChillerExample.WaterCooledChillerExample7_11mix.c WaterCooledChillerExample.WaterCooledChillerExample7_12jac.c WaterCooledChillerExample.WaterCooledChillerExample7_13opt.c WaterCooledChillerExample.WaterCooledChillerExample7_14lnz.c \
WaterCooledChillerExample.WaterCooledChillerExample7_15syn.c WaterCooledChillerExample.WaterCooledChillerExample7_16dae.c WaterCooledChillerExample.WaterCooledChillerExample7_17inl.c WaterCooledChillerExample.WaterCooledChillerExample7_18spd.c \
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part0.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part1.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part2.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part3.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part4.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part5.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part6.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part7.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_08bnd_part8.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_06inz_part0.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_06inz_part1.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_06inz_part2.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_06inz_part3.c\
   WaterCooledChillerExample.WaterCooledChillerExample7_06inz_part4.c

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) WaterCooledChillerExample.WaterCooledChillerExample7.makefile WaterCooledChillerExample.WaterCooledChillerExample7_literals.h WaterCooledChillerExample.WaterCooledChillerExample7_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that WaterCooledChillerExample.WaterCooledChillerExample7_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) WaterCooledChillerExample.WaterCooledChillerExample7_functions.h WaterCooledChillerExample.WaterCooledChillerExample7_literals.h $(OFILES)
	$(CC) -I. -o WaterCooledChillerExample.WaterCooledChillerExample7$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) WaterCooledChillerExample.WaterCooledChillerExample7_functions.h WaterCooledChillerExample.WaterCooledChillerExample7_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o WaterCooledChillerExample.WaterCooledChillerExample7$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f WaterCooledChillerExample.WaterCooledChillerExample7_records.o $(MAINOBJ)

bundle:
	@tar -cvf WaterCooledChillerExample.WaterCooledChillerExample7_Files.tar $(GENERATEDFILES)