# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=-municode $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Buildings 6.0.0/Resources/C-Sources" -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=logic3_raw -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=3 -DOMC_NUM_NONLINEAR_SYSTEMS=28 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lryu -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lsz -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/irfan/OneDrive/Documents/GitHub/PB/WaterCooledChillerExample/Trial_Final"
MAINFILE=logic3_raw.c
MAINOBJ=logic3_raw.o
CFILES=logic3_raw_functions.c logic3_raw_records.c \
logic3_raw_01exo.c logic3_raw_02nls.c logic3_raw_03lsy.c logic3_raw_04set.c logic3_raw_05evt.c logic3_raw_06inz.c logic3_raw_07dly.c \
logic3_raw_08bnd.c logic3_raw_09alg.c logic3_raw_10asr.c logic3_raw_11mix.c logic3_raw_12jac.c logic3_raw_13opt.c logic3_raw_14lnz.c \
logic3_raw_15syn.c logic3_raw_16dae.c logic3_raw_17inl.c logic3_raw_18spd.c \
   logic3_raw_08bnd_part0.c\
   logic3_raw_08bnd_part1.c\
   logic3_raw_08bnd_part2.c\
   logic3_raw_08bnd_part3.c\
   logic3_raw_08bnd_part4.c\
   logic3_raw_08bnd_part5.c\
   logic3_raw_08bnd_part6.c\
   logic3_raw_06inz_part0.c\
   logic3_raw_06inz_part1.c\
   logic3_raw_06inz_part2.c

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) logic3_raw.makefile logic3_raw_literals.h logic3_raw_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that logic3_raw_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) logic3_raw_functions.h logic3_raw_literals.h $(OFILES)
	$(CC) -I. -o logic3_raw$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/mingw64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/ucrt64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/win64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) logic3_raw_functions.h logic3_raw_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/mingw64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/ucrt64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/win64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o logic3_raw$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/mingw64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/ucrt64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library/win64" "-LC:/Users/irfan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f logic3_raw_records.o $(MAINOBJ)

bundle:
	@tar -cvf logic3_raw_Files.tar $(GENERATEDFILES)