# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=-municode $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Buildings 6.0.0/Resources/C-Sources" -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=outputs_WaterCooledChillerExample7 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=7 -DOMC_NUM_NONLINEAR_SYSTEMS=23 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lryu -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lsz -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample"
MAINFILE=outputs/WaterCooledChillerExample7.c
MAINOBJ=outputs/WaterCooledChillerExample7.o
CFILES=outputs/WaterCooledChillerExample7_functions.c outputs/WaterCooledChillerExample7_records.c \
outputs/WaterCooledChillerExample7_01exo.c outputs/WaterCooledChillerExample7_02nls.c outputs/WaterCooledChillerExample7_03lsy.c outputs/WaterCooledChillerExample7_04set.c outputs/WaterCooledChillerExample7_05evt.c outputs/WaterCooledChillerExample7_06inz.c outputs/WaterCooledChillerExample7_07dly.c \
outputs/WaterCooledChillerExample7_08bnd.c outputs/WaterCooledChillerExample7_09alg.c outputs/WaterCooledChillerExample7_10asr.c outputs/WaterCooledChillerExample7_11mix.c outputs/WaterCooledChillerExample7_12jac.c outputs/WaterCooledChillerExample7_13opt.c outputs/WaterCooledChillerExample7_14lnz.c \
outputs/WaterCooledChillerExample7_15syn.c outputs/WaterCooledChillerExample7_16dae.c outputs/WaterCooledChillerExample7_17inl.c outputs/WaterCooledChillerExample7_18spd.c \
   outputs/WaterCooledChillerExample7_08bnd_part0.c\
   outputs/WaterCooledChillerExample7_08bnd_part1.c\
   outputs/WaterCooledChillerExample7_08bnd_part2.c\
   outputs/WaterCooledChillerExample7_08bnd_part3.c\
   outputs/WaterCooledChillerExample7_08bnd_part4.c\
   outputs/WaterCooledChillerExample7_08bnd_part5.c\
   outputs/WaterCooledChillerExample7_08bnd_part6.c\
   outputs/WaterCooledChillerExample7_08bnd_part7.c\
   outputs/WaterCooledChillerExample7_08bnd_part8.c\
   outputs/WaterCooledChillerExample7_06inz_part0.c\
   outputs/WaterCooledChillerExample7_06inz_part1.c\
   outputs/WaterCooledChillerExample7_06inz_part2.c\
   outputs/WaterCooledChillerExample7_06inz_part3.c\
   outputs/WaterCooledChillerExample7_06inz_part4.c

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) outputs/WaterCooledChillerExample7.makefile outputs/WaterCooledChillerExample7_literals.h outputs/WaterCooledChillerExample7_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that outputs/WaterCooledChillerExample7_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) outputs/WaterCooledChillerExample7_functions.h outputs/WaterCooledChillerExample7_literals.h $(OFILES)
	$(CC) -I. -o outputs/WaterCooledChillerExample7$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/WaterCooledChillerExample" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library" -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) outputs/WaterCooledChillerExample7_functions.h outputs/WaterCooledChillerExample7_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/WaterCooledChillerExample" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library" -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o outputs/WaterCooledChillerExample7$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.27.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.27.0-64bit/lib/" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/WaterCooledChillerExample" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/WaterCooledChillerExample/Resources/Library" -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/mingw64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/ucrt64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library/win64" "-LC:/Users/Irvan/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.2+maint.om/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f outputs/WaterCooledChillerExample7_records.o $(MAINOBJ)

bundle:
	@tar -cvf outputs/WaterCooledChillerExample7_Files.tar $(GENERATEDFILES)